---
- name: Include variables based on distro or family
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: Download HTML source for Slack download page
  get_url:
    url: "{{ slack_download_url }}"
    dest: "{{ slack_html_src }}"
    tmp_dest: "{{ slack_tmp_dir }}"

- name: Copy sed script
  copy:
    src: list_urls.sed
    dest: "{{ slack_tmp_dir }}"
    mode: 0777

- name: Find latest package to download
  shell: "{{ slack_tmp_dir }}/list_urls.sed {{ slack_html_src }} | grep '\\.{{ slack_package_format }}'| sort -u"
  register: registered_download_url
  changed_when: False

- name: Download Slack
  get_url:
    url: "{{ item }}"
    dest: "{{ slack_package }}"
    tmp_dest: "{{ slack_tmp_dir }}"
  with_items: "{{ registered_download_url.stdout }}"

- include_tasks: "{{ ansible_os_family }}.yml"
